# 动态配置（用户自定义配置）文件
# 使用前，需要视实际情况进行修改
musicFactory:
  base:
    audioFileDirectory: '< 使用前，请先根据功能编号，自定义原始音频文件存放目录！>' # 原始音频文件的存放位置。
    convert:
      convertedAudioFileDirectory: '< 使用前，请先根据功能编号，自定义转换格式后的音频文件存放目录！>' # 转换格式后的音频文件存放位置。
      formatConverterId: 1
    albumPictureCompression:
      albumPictureCompressedAudioFileDirectory: '< 使用前，请先根据功能编号，自定义专辑封面压缩后的音频文件存放目录！>' # 专辑封面压缩后的音频文件存放位置。
      compressPixelValue: 500 # 音频文件专辑封面压缩的像素值（长宽像素值相同）。
  filters:
    analyzingInfoForAudioFile:
      songLyricsFilter: true # 设置是否以歌曲内嵌歌词的有无，作为文件是否需要进行元数据信息补全的依据。true - 验证歌曲内嵌歌词是否存在；false - 跳过验证歌曲内嵌歌词。
      albumArtistFilter: true # 设置是否以歌曲所属专辑的艺术家的有无，作为文件是否需要进行元数据信息补全的依据。true - 验证歌曲所属专辑的艺术家是否存在；false - 跳过验证歌曲所属专辑的艺术家。
      albumPublishDateFilter: true # 设置是否以歌曲所属专辑的发布时间的有无，作为文件是否需要进行元数据信息补全的依据。true - 验证歌曲所属专辑的发布时间是否存在；false - 跳过验证歌曲所属专辑的发布时间。
      albumDescriptionFilter: true # 设置是否以歌曲所属专辑的描述的有无，作为文件是否需要进行元数据信息补全的依据。true - 验证歌曲所属专辑的描述是否存在；false - 跳过验证歌曲所属专辑的描述。
      albumLanguageFilter: true # 设置是否以歌曲所属专辑的语言类型的有无，作为文件是否需要进行元数据信息补全的依据。true - 验证歌曲所属专辑的语言类型是否存在；false - 跳过验证歌曲所属专辑的语言类型。
      albumCopyrightFilter: true # 设置是否以歌曲所属专辑的版权信息的有无，作为文件是否需要进行元数据信息补全的依据。true - 验证歌曲所属专辑的版权信息是否存在；false - 跳过验证歌曲所属专辑的版权信息。
